apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-environment-configs
spec:
  package: xpkg.upbound.io/crossplane-contrib/function-environment-configs:v0.2.0
---
apiVersion: apiextensions.crossplane.io/v1alpha1
kind: EnvironmentConfig
metadata:
  name: tkp
data:
  env: sandbox
  aws.account-id: '851725299431'
  aws.account-alias: tkp-sandbox-2
  aws.region: eu-west-1
---
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-auto-ready
spec:
  package: xpkg.upbound.io/upbound/function-auto-ready:v0.4.2
---
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-kcl
spec:
  package: xpkg.upbound.io/crossplane-contrib/function-kcl:v0.11.3
---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  labels:
    provider: aws
  name: buckets
spec:
  compositeTypeRef:
    apiVersion: workshop.tkp.nl/v1alpha1
    kind: Bucket
  mode: Pipeline
  pipeline:
    - functionRef:
        name: function-environment-configs
      step: environmentConfigs
      input:
        apiVersion: environmentconfigs.fn.crossplane.io/v1beta1
        kind: Input
        spec:
          environmentConfigs:
            - ref:
                name: tkp
    - functionRef:
        name: function-kcl
      step: create-resources
      input:
        apiVersion: krm.kcl.dev/v1alpha1
        kind: KCLInput
        metadata:
          name: basic
        spec:
          source: |-
            
            import yaml
            
            env = option("params").ctx['apiextensions.crossplane.io/environment']
            oxr = option("params").oxr
            name = oxr.metadata.name
            spec = oxr.spec
            
            items = [
                {
                    apiVersion = "s3.aws.upbound.io/v1beta2"
                    kind = "Bucket"
                    metadata = {
                        name = name
                    }
                    spec = {
                        deletionPolicy = "Orphan"
                        forProvider = {
                            region = env["aws.region"]
                            tags = spec.tags
                        }
                    }
                }
                {
                    apiVersion = "s3.aws.upbound.io/v1beta2"
                    kind = "BucketVersioning"
                    metadata = {
                        name = "${name}-versioning"
                    }
                    spec = {
                        forProvider = {
                            region = env["aws.region"]
                            bucketSelector.matchControllerRef = True
                            versioningConfiguration = {
                                status = "Enabled"
                            }
                        }
                    }
                }
                {
                    apiVersion = "s3.aws.upbound.io/v1beta2"
                    kind = "BucketLifecycleConfiguration"
                    metadata = {
                        name = "${name}-lifecycle-policy"
                    }
                    spec = {
                        forProvider = {
                            region = env["aws.region"]
                            bucketSelector.matchControllerRef = True
                            $rule = [
                                {
                                    id = "archive"
                                    $filter = {
                                        prefix = "/"
                                    }
                                    noncurrentVersionExpiration = {
                                        noncurrentDays = 90
                                    }
                                    status = "Enabled"
                                }
                            ]
                        }
                    }
                }
            ]
    - functionRef:
        name: function-auto-ready
      step: automatically-detect-ready-composed-resources