apiVersion: s3.aws.upbound.io/v1beta2
kind: Bucket
metadata:
  name: timo-workshop-bucket
spec:
  deletionPolicy: Orphan
  forProvider:
    region: eu-west-1
    tags:
      IAC-tool: crossplane
      Afdeling: IT4IT
      Medewerker: kanters.t@tkppensioen.nl
---
apiVersion: s3.aws.upbound.io/v1beta2
kind: BucketVersioning
metadata:
  name: timo-workshop-bucket-versioning
spec:
  forProvider:
    region: eu-west-1
    bucket: timo-workshop-bucket
    versioningConfiguration:
      status: Enabled
---
apiVersion: s3.aws.upbound.io/v1beta2
kind: BucketLifecycleConfiguration
metadata:
  name: timo-workshop-bucket-lifecycle-policy
spec:
  forProvider:
    region: eu-west-1
    bucket: timo-workshop-bucket
    rule:
      - id: archive
        filter:
          prefix: /
        noncurrentVersionExpiration:
          noncurrentDays: 90
        status: Enabled
